In [2]:
import pandas as pd

# 파이썬의 단점과 numpy
_**느리다.**_   
_**쓰레드를 사용할 수 없다.**_

- 그러나 numpy 라는 라이브러리가 나타나면서 느린 속도를 극복했다.
- 수 많은 라이브러리가 numpy 를 활용하여 만들어졌다.
- 특히 수학, 과학적 계산에서 그렇다.
- 파이썬은 접착이 가능한 언어이다.
- 그래서 c 로 구현한 numpy 로 속도의 한계를 극복할 수 있었다.

# pandas 
- pandas 역시 numpy 를 wrapping 하여 만든 library 이다.
- 그래서 속도가 빠르다.
- pandas 는 Series 와 DataFrame 이라는 데이타 타입을 갖는다.

# Series data type

In [106]:
# Series 는 numpy 를 기반으로 만들어진다.
# pandas 가 numpy 를 기반으로 만들었으니까...
# list 를 입력 받아서 Series 를 생성할 수 있다.
# 단, list 의 원소들은 같은 타입이어야 한다.
# 다른 타입의 데이터를 원소로 가질 경우, dtype 이 object 로 결정된다.

pd.Series([1, 2, 3, 4])

0    1
1    2
2    3
3    4
dtype: int64

In [101]:
# dictionary 를 받아서 Series 를 생성할 수 있다.
# key 는 숫자와 문자(문자열)만 가능하다.

pd.Series({'a':1, 'b':2 ,'c':3, 'd':4, 99.:5, 100:6, '이름':7})

a       1
b       2
c       3
d       4
99.0    5
100     6
이름      7
dtype: int64

In [99]:
# numpy 의 ndarray 를 받아서 Series 를 생성할 수 있다.

pd.Series(np.arange(1, 5, 1))

0    1
1    2
2    3
3    4
dtype: int64

In [110]:
# data 와 index 를 직접 지정할 수 있다.
# data 의 개수와 index 의 개수는 일치해야 한다.

a = pd.Series(
    data = [1, 2, 3, 4, 5, 6],
    index = ['a', 'b', 3, 4.9, 'moon', 'f']
)
a

a       1
b       2
3       3
4.9     4
moon    5
f       6
dtype: int64

In [111]:
type(a)

pandas.core.series.Series

In [112]:
# Series.head() 함수는 기본적으로 처음 5개의 원소를 보여준다.

a.head()

a       1
b       2
3       3
4.9     4
moon    5
dtype: int64

In [113]:
a.head(2)

a    1
b    2
dtype: int64

In [3]:
import numpy as np

In [115]:
# np.nan 는 not a number 의 약자로써 숫자가 아님을 의미한다.
# 하지만 np.nan 의 타입은 float 로 취급된다.
# Series 에 np.nan 가 존재하면 다른 원소들도 모두 float 로 변환된다.
# Series 의 원소들은 모두 타입이 같아야 하기 때문이다.

a = pd.Series([1, 2, 1, np.nan])
a

0    1.0
1    2.0
2    1.0
3    NaN
dtype: float64

In [116]:
type(np.nan)

float

In [117]:
np.nan

nan

In [118]:
# len 은 원소의 개수를 의미한다.
# 따라서 np.nan 도 포함된다.

len(a)

4

In [119]:
# Series.shape 속성은 np.nan 가 차지하고 있는 위치를 인정한다.

a.shape

(4,)

In [120]:
# Series.unique() 함수는 중복 원소를 제거하고 보여준다.
# np.nan 도 포함한다.

a.unique()

array([ 1.,  2., nan])

In [123]:
# 결과는 numpy.ndarray 이다.

type(a.unique())

numpy.ndarray

In [122]:
# 반면 Series.count() 함수는 np.nan 를 세지 않는다.
# count() 는 유효한 원소의 개수를 의미한다.

a.count()

3

In [82]:
# Series.value_counts() 함수 역시 np.nan 를 무시한다.
# 유효한 원소들에 대하여 각각의 개수를 센다.
# 본래 Series 의 값들이 index 가 되고, 각 값들의 개수가 value 가 된다.

a.value_counts()

1.0    2
2.0    1
dtype: int64

In [83]:
# unique() 가 numpy.ndarray 타입을 반환했다면..
# value_counts() 는 Series 타입을 반환한다.

type(a.value_counts())

pandas.core.series.Series

In [86]:
# Series 간의 연산은 index 에 대하여 진행된다.
# 연산이 이루어질 index 가 존재하지 않으면 nan 와의 연산이 진행되고..
# nan 와의 연산 결과는 nan 이다.

a1 = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])
a2 = pd.Series([4, 3, 2, 1], index = ['b', 'c', 'e', 'f'])
a1 + a2

a    NaN
b    6.0
c    6.0
d    NaN
e    NaN
f    NaN
dtype: float64

# DataFrame data type

In [107]:
# DataFrame 은 여러개의 Series 들을 변수로 관리할 수 있도록 만든 데이터 타입이다.
# 같은 index 를 갖는 Series 들을 효율적으로 다루기 위해 DataFrame 을 활용할 수 있다.
# DataFrame 은 Series 의 dictionary 형태이다.
# Series 들은 DataFrame 의 column 을 구성한다.

a1 = pd.Series([1, 2, 3, 4])
b1 = pd.Series([5, 6, 7, 8])
pd.DataFrame({'a':a1, 'b':b1})

   a  b
0  1  5
1  2  6
2  3  7
3  4  8

In [109]:
a1 = np.arange(1, 10, 2);
b1 = np.arange(10, 20, 2);
pd.DataFrame({'a':a1, 'b':b1})

   a   b
0  1  10
1  3  12
2  5  14
3  7  16
4  9  18

In [124]:
# index 와 column 을 따로 명시하지 않을 경우
# list or numpy.ndarray 를 통해 직관적으로 DataFrame 을 생성할 수 있다.

pd1 = pd.DataFrame([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
pd1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [125]:
np1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

df1 = pd.DataFrame(np1)
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [139]:
# DataFrame 을 생성할 때 column 과 index 를 설정할 수 있다.
# 파라미터 이름으로 매핑하지 않으면 파라미터의 순서를 주의해야 한다.
# data, index, columns 의 순서로 파라미터가 온다.

data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
index=['r1', 'r2', 'r3']
columns=['c1', 'c2', 'c3']

df1 = pd.DataFrame(data, columns=columns, index=index)
df1

    c1  c2  c3
r1   1   2   3
r2   4   5   6
r3   7   8   9

In [4]:
# index 가 다른 Series 로 DataFrame 을 구성하면..
# 모든 index 를 구성하고, 없는 데이터는 nan 으로 채운다.

a1 = pd.Series(data=[1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
a2 = pd.Series(data=[5, 6, 7, 8], index=['b', 'c', 'd', 'f'])
df = pd.DataFrame({'c1':a1, 'c2':a2})
df

    c1   c2
a  1.0  NaN
b  2.0  5.0
c  3.0  6.0
d  4.0  7.0
f  NaN  8.0

In [5]:
# DataFrame 은 Series 를 value 로 갖는 dictionary 라고 생각할 수 있다.
# 따라서 다음과 같이 Series 를 추가할 수 있다.

a3 = pd.Series([11, 12, 13, 14], index=['a', 'b', 'c', 'f'])
df['c3'] = a3;
df

    c1   c2    c3
a  1.0  NaN  11.0
b  2.0  5.0  12.0
c  3.0  6.0  13.0
d  4.0  7.0   NaN
f  NaN  8.0  14.0