In [2]:
import numpy as np
import pandas as pd

In [5]:
# 하나의 cell 에서 multiple output 출력을 가능하게 하는 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [8]:
df = pd.read_csv("./naver_finance/2015_12.csv")
df.head()

,ticker,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),price,price2
0,AK홀딩스,28071.4790,3.787,-1.334,-374.43063,-7.677,-1.421,15.1196,-3245.7412,43497.723,211899.220,-19.47167,1.45295,0.29825,63200.0,56000.0
1,BGF,43342.8000,4.236,3.526,1528.41270,22.771,10.327,271.9567,3071.8716,15605.457,87779.875,28.77862,5.66495,1.00711,44202.0,42140.0
2,BNK금융지주,51740.2540,13.455,10.253,5304.71200,9.116,0.609,NaN,1853.1799,21665.062,19749.037,4.54354,0.38864,0.42635,8420.0,8680.0
3,BYC,1821.9598,11.598,7.222,131.58138,3.546,2.024,13.2353,15693.8080,453030.620,216899.980,29.27907,1.01428,2.11849,459500.0,397000.0
4,CJ,211667.0800,5.789,2.604,5511.15530,5.874,2.365,5.8208,5780.6260,110304.560,594563.900,40.94442,2.14574,0.39808,236684.0,176334.0

# EDA - exploratory data analysis

## Metadata

### info()

In [21]:
# 데이터에 대한 데이터를 먼저 파악한다.

df.shape
# df.get_dtype_counts()
df.dtypes
df.dtypes.value_counts()

print("===================================================")
df.info()

(681, 16)

ticker        object
매출액(억원)      float64
영업이익률(%)     float64
순이익률(%)      float64
당기순이익(억원)    float64
ROE(%)       float64
ROA(%)       float64
ROIC(%)      float64
EPS(원)       float64
BPS(원)       float64
SPS(원)       float64
PER(배)       float64
PBR(배)       float64
PSR(배)       float64
price        float64
price2       float64
dtype: object

float64    15
object      1
dtype: int64

===================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681 entries, 0 to 680
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ticker     681 non-null    object
 1   매출액(억원)    680 non-null    float64
 2   영업이익률(%)   680 non-null    float64
 3   순이익률(%)    680 non-null    float64
 4   당기순이익(억원)  680 non-null    float64
 5   ROE(%)     665 non-null    float64
 6   ROA(%)     665 non-null    float64
 7   ROIC(%)    611 non-null    float64
 8   EPS(원)     681 non-null    float64
 9   BPS(원)     681 non-null    float64
 10  SPS(원)     681 non-null    float64
 11  PER(배)     668 non-null    float64
 12  PBR(배)     681 non-null    float64
 13  PSR(배)     668 non-null    float64
 14  price      681 non-null    float64
 15  price2     681 non-null    float64
dtypes: float64(15), object(1)
memory usage: 85.2+ KB

In [24]:
a1 = df['ticker']
a1.dtype
a1

dtype('O')

0        AK홀딩스
1          BGF
2      BNK금융지주
3          BYC
4           CJ
        ...
676        휴비스
677        휴스틸
678        휴켐스
679       흥국화재
680       흥아해운
Name: ticker, Length: 681, dtype: object

In [26]:
df = df.rename(columns={"ticker":"종목명", "price":"가격"})
df.head()

,종목명,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),가격,price2
0,AK홀딩스,28071.4790,3.787,-1.334,-374.43063,-7.677,-1.421,15.1196,-3245.7412,43497.723,211899.220,-19.47167,1.45295,0.29825,63200.0,56000.0
1,BGF,43342.8000,4.236,3.526,1528.41270,22.771,10.327,271.9567,3071.8716,15605.457,87779.875,28.77862,5.66495,1.00711,44202.0,42140.0
2,BNK금융지주,51740.2540,13.455,10.253,5304.71200,9.116,0.609,NaN,1853.1799,21665.062,19749.037,4.54354,0.38864,0.42635,8420.0,8680.0
3,BYC,1821.9598,11.598,7.222,131.58138,3.546,2.024,13.2353,15693.8080,453030.620,216899.980,29.27907,1.01428,2.11849,459500.0,397000.0
4,CJ,211667.0800,5.789,2.604,5511.15530,5.874,2.365,5.8208,5780.6260,110304.560,594563.900,40.94442,2.14574,0.39808,236684.0,176334.0

### describe()

In [29]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)
df.describe()

,매출액(억원),영업이익률(%),순이익률(%),당기순이익(억원),ROE(%),ROA(%),ROIC(%),EPS(원),BPS(원),SPS(원),PER(배),PBR(배),PSR(배),가격,price2
count,680.000,680.000,680.000,680.000,665.000,665.000,611.000,681.000,681.000,681.000,668.000,681.000,668.000,681.000,681.000
mean,30112.802,3.882,7.669,1312.761,4.512,1.837,-3.009,426.081,47451.880,95471.752,18.921,1.582,1.922,47344.200,41784.562
std,108134.170,13.143,151.567,10133.596,130.083,9.512,195.156,34193.002,152959.285,316794.457,134.916,2.040,19.849,117063.700,96318.573
min,3.561,-191.601,-193.426,-22092.438,-529.306,-136.813,-4685.987,-844700.060,-230961.190,50.177,-1435.921,-2.829,0.011,158.000,154.000
25%,1727.089,1.532,0.369,10.859,0.828,0.275,1.357,22.964,4110.551,7504.220,4.674,0.622,0.310,3903.000,4060.000
50%,4692.060,4.194,3.067,118.918,5.350,2.305,5.208,539.109,10988.989,22559.920,11.743,0.957,0.590,12018.000,10900.000
75%,15243.673,8.314,6.612,504.201,9.766,5.338,10.550,2197.652,39550.230,72356.336,24.062,1.672,1.142,40496.000,39750.000
max,2006534.900,64.273,3923.338,190601.440,3122.573,60.287,271.957,93713.010,3017474.000,5553036.500,2808.262,21.154,511.718,1225000.000,1064000.000

In [39]:
# 수치값들을 대상으로 개수, 평균, 편차, 최소, 최대, 4분위 등을 보여준다.
# 수치값이 아닌 Series 들을 drop 한다.
# include 옵션을 통해 어떤 Series 들을 대상으로 할 것인지 지정할 수 있다.

# df.describe().T 
df.describe(include=[np.int64, np.float64]).T.head()

,count,mean,std,min,25%,50%,75%,max
매출액(억원),680.000,30112.802,108134.170,3.561,1727.089,4692.060,15243.673,2006534.900
영업이익률(%),680.000,3.882,13.143,-191.601,1.532,4.194,8.314,64.273
순이익률(%),680.000,7.669,151.567,-193.426,0.369,3.067,6.612,3923.338
당기순이익(억원),680.000,1312.761,10133.596,-22092.438,10.859,118.918,504.201,190601.440
ROE(%),665.000,4.512,130.083,-529.306,0.828,5.350,9.766,3122.573

In [41]:
# 4분위가 아닌 임의의 퍼센트를 지정하여 볼 수 있다.

df.describe(percentiles=[0.01, 0.1, 0.9]).T.head()

,count,mean,std,min,1%,10%,50%,90%,max
매출액(억원),680.000,30112.802,108134.170,3.561,90.991,796.897,4692.060,55667.786,2006534.900
영업이익률(%),680.000,3.882,13.143,-191.601,-24.020,-4.304,4.194,12.705,64.273
순이익률(%),680.000,7.669,151.567,-193.426,-60.643,-7.085,3.067,11.185,3923.338
당기순이익(억원),680.000,1312.761,10133.596,-22092.438,-7180.579,-173.444,118.918,1851.929,190601.440
ROE(%),665.000,4.512,130.083,-529.306,-172.499,-14.753,5.350,15.462,3122.573

In [46]:
# describe() 의 대상을 수치가 아닌 값으로 할 경우..
# 가장 빈도수가 높은 항목에 대한 정보를 확인할 수 있다.
# 혹은 특정 데이터의 타입을 제외할 수도 있다.

df.describe(include=[pd.Categorical]).T
df.describe(exclude=[np.number]).T

    count unique    top freq
종목명   681    681  AK홀딩스    1

    count unique    top freq
종목명   681    681  AK홀딩스    1

### unique(), value_counts()

In [56]:
# Series.unique() 는 중복되지 않게 원소들을 하나씩 선택하여 numpy.ndarray 를 반환한다.
# Series.unique() 는 nan 를 포함한다.
# DataFrame.nunique() 는 각 Series 에 대하여 유일한 값의 데이터들을 센다.
# DataFrame.nunique() 는 nan 를 무시하고 센다.

a1 = pd.Series([1, 1, 3], index=['a', 'b', 'c'])
a2 = pd.Series([4, 5, 6], index=['a', 'b', 'd'])
df1 = pd.DataFrame({'r1':a1, 'r2':a2})
df1
df1.nunique()
df.nunique()

     r1    r2
a 1.000 4.000
b 1.000 5.000
c 3.000   NaN
d   NaN 6.000

r1    2
r2    3
dtype: int64

종목명          681
매출액(억원)      680
영업이익률(%)     667
순이익률(%)      672
당기순이익(억원)    680
ROE(%)       655
ROA(%)       650
ROIC(%)      610
EPS(원)       681
BPS(원)       681
SPS(원)       681
PER(배)       668
PBR(배)       680
PSR(배)       668
가격           628
price2       620
dtype: int64

In [68]:
# Series 에는 unique(), nunique(), value_counts() 3가지를 사용할 수 있다.

a1 = pd.Series([1, 1, 3, np.nan], index=['a', 'b', 'c', 'd'])
a2 = pd.Series([4, 5, 6, 7], index=['a', 'b', 'd', 'e'])
df1 = pd.DataFrame({'r1':a1, 'r2':a2})

a1.unique() # nan 를 센다.
a1.nunique() 
a1.value_counts()

df1.nunique()
df1.value_counts()

array([ 1.,  3., nan])

2

1.000    2
3.000    1
dtype: int64

r1    2
r2    4
dtype: int64

r1     r2
1.000  4.000    1
       5.000    1
dtype: int64