# 가장 처음에 실행되었다고 가정하는 코드

In [1]:
import numpy as np
import pandas as pd

In [7]:
# 하나의 cell 에서 multiple output 출력을 가능하게 하는 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# pandas DataFrame 의 사이즈가 큰 경우, 어떻게 화면에 출력을 할지 셋팅하는 코드
pd.set_option('display.float_format', lambda x: '%.3f' % x)
pd.set_option('max_columns', None)

# index

In [12]:
# Series 의 경우 index 속성에 다른 값을 대압하여 index 자체를 바꿀 수 있다.
# 그러나 data 는 index 교체와 같은 방법으로 바꿀 수 없다.

s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s1
s1.index = ['가', '나', '다', '라']
s1.data = [5, 6, 7, 8]
s1

a    1
b    2
c    3
d    4
dtype: int64

가    1
나    2
다    3
라    4
dtype: int64

In [35]:
# DataFrame 의 경우 set_index() 함수를 통해 특정 column(Series)를 index 로 설정할 수 있다.
# 자신이 포함하고 있는 Series 의 column 을 빼내어 index 로 지정하거나
# 새로운 Series 를 index 로 지정할 수 있다.
a1 = pd.Series([1, 2, 3])
a2 = pd.Series([4, 5, 6])
a3 = pd.Series(['a', 'b', 'c'])
df1 = pd.DataFrame({'r1':a1, 'r2':a2, 'r3':a3})
df1 #1)


# 자신이 소유한 Series 를 index 로 지정..
df2 = df1.set_index('r3') 
df1 #2) 기존의 DataFrame 은 유지 
df2 #3) 새롭게 DataFrame 을 생성하여 반환


# 새로운 Series 를 index 로 지정..
df3 = df1.set_index(a3)
df1 #4) 기존의 DataFrame 은 유지 
df3 #5) 새롭게 DataFrame 을 생성하여 반환


# DataFrame 에 새로운 Series 를 추가할 때, dictionary 방식으로 추가할 수 있다.
# 1.기존의 컬럼을 덮어쓸 수 있다.
# 2.새롭게 컬럼을 추가할 수 있다.
# 3.추가되는 컬럼의 index 중에 DataFrame 에 존재하는 index 만 처리된다. 
df3['r3'] = pd.Series([11, 22, 33], index=['a', 'b', 'c'])
df3['r4'] = pd.Series([44, 55, 66], index=['a', 'b', 'c'])
df3['r5'] = pd.Series([77, 88, 99], index=['c', 'd', 'e'])
df3 #6)

   r1  r2 r3
0   1   4  a
1   2   5  b
2   3   6  c

   r1  r2 r3
0   1   4  a
1   2   5  b
2   3   6  c

    r1  r2
r3
a    1   4
b    2   5
c    3   6

   r1  r2 r3
0   1   4  a
1   2   5  b
2   3   6  c

   r1  r2 r3
a   1   4  a
b   2   5  b
c   3   6  c

   r1  r2  r3  r4     r5
a   1   4  11  44    NaN
b   2   5  22  55    NaN
c   3   6  33  66 77.000

In [43]:
# 기존의 DataFrame 에서 특정 index 들을 골라서 별도의 DataFrame 을 만들 수 있다.
# 기존의 DataFrame 은 그대로 유지되고, 새로 생성한 DataFrame 을 반환한다.

df4 = df3.reindex(['a', 'b', 'd'])
df3
df4

   r1  r2  r3  r4     r5
a   1   4  11  44    NaN
b   2   5  22  55    NaN
c   3   6  33  66 77.000

     r1    r2     r3     r4  r5
a 1.000 4.000 11.000 44.000 NaN
b 2.000 5.000 22.000 55.000 NaN
d   NaN   NaN    NaN    NaN NaN

In [49]:
# DataFrame 이든 Series 든 index 를 주의깊게 잘 구분해야 한다.
# 숫자와 문자는 다른 타입이다.

a1 = pd.Series([1, 2, 3], index=['1', '2', '3'])
a2 = pd.Series([4, 5, 6], index=[1, 2, 3])
a1
a2

# a1 과 a2 는 출력 결과를 보면 index 가 같아 보인다.
# 하지만 index 의 타입이 다르기 때문에 다르다.

a1 + a2
a1.index
a2.index
type(a1.index)

1    1
2    2
3    3
dtype: int64

1    4
2    5
3    6
dtype: int64

1   NaN
2   NaN
3   NaN
1   NaN
2   NaN
3   NaN
dtype: float64

Index(['1', '2', '3'], dtype='object')

Int64Index([1, 2, 3], dtype='int64')

pandas.core.indexes.base.Index

In [55]:
a1 = pd.Series([1, 2, 3], index=['1', '2', '3'])
a2 = pd.Series([4, 5, 6], index=[1, 2, 3])
a1
a2

# index 의 데이터타입을 바꿀 수 있다.
# 핵심은 Series 끼리 연산을 하려면 반드시 index 가 같아야 한다는 것이다.

a1.index = a1.index.astype(int)
a1 + a2

1    1
2    2
3    3
dtype: int64

1    4
2    5
3    6
dtype: int64

1    5
2    7
3    9
dtype: int64

In [69]:
# reindex() 는 기존의 DataFrame 에서 원하는 row 들을 골라서 새로운 DataFrame 을 생성하는 것이다.
# 이 때, 새로운 index 에는 nan 가 채워지는 것이 기본이다.
# 하지만 필요에 따라 특정 값을 채울 수 있다.

a1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
a2 = pd.Series([4, 5, 6], index=['e', 'b', 'c'])
df1 = pd.DataFrame({'r1':a1, 'r2':a2})
df1


# fill_value 는 기존의 nan 을 바꾸지는 않는다.
# 새롭게 추가되는 nan 를 대체할 값이다.
# method='ffill' 은 forward fill 의 의미다.
# 이전의 값을 가져와 채운다는 의미다.
# 채우기 위해 가져오는 이전의 값이 무엇인지 주의깊게 보아야 한다.

df1.reindex(['a', 'b', 'f'])
df1.reindex(['a', 'b', 'f'], fill_value=0)
df1.reindex(['a', 'b', 'd'], method='ffill')

     r1    r2
a 1.000   NaN
b 2.000 5.000
c 3.000 6.000
e   NaN 4.000

     r1    r2
a 1.000   NaN
b 2.000 5.000
f   NaN   NaN

     r1    r2
a 1.000   NaN
b 2.000 5.000
f 0.000 0.000

     r1    r2
a 1.000   NaN
b 2.000 5.000
d 3.000 6.000